apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: max-weather
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: max-weather
  syncPolicy:
    automated:
      prune: true
  source:
    path: helmcharts
    repoURL: https://MY_INFRA_REPOSITORY/infrastructure.git
    targetRevision: HEAD
